      <footer>
        <a href="https://plus.google.com/106817884636579207205" rel="publisher">Google+</a>
        <a class="impressum" href="/impressum">Impressum</a>
      </footer>
    </div>
    <!-- TODO: include google analytics -->
    <script src="https://rawgit.com/ruyadorno/simple-slider/master/dist/simpleslider.min.js"></script>
    <script>
      simpleslider.getSlider({
        container: document.querySelector('.front-slider .slider'),
        init: 100,
        show: 0,
        end: -100,
        unit: '%',
        delay: 3,
        duration: 1
      });
    </script>

    <script src="<?php echo get_template_directory_uri() . '/bundle.js' ?>"></script>
  </body>
</html>
