<div class="hero front-slider">
  <div class="container">
    <div class="columns fake-item slider-item is-gapless">
      <div class="column is-half slider-image"><img src="<?php echo get_bloginfo('template_url') ?>/images/slider/1.jpg"></div>
      <div class="column is-half slider-text is-size-3-desktop is-size-5-tablet is-size-6-mobile">Wir sind die Abteilung Tischtennis des Berliner Sportvereins SG Bergmann Borsig e.V. aus Pankow</div>
    </div>

    <div class="slider-wrapper">
      <div class="slider">
        <div class="columns slider-item is-gapless">
          <div class="column is-half slider-image"><img src="<?php echo get_bloginfo('template_url') ?>/images/slider/1.jpg"></div>
          <div class="column is-half slider-text is-size-3-desktop is-size-5-tablet is-size-6-mobile">Wir sind die Abteilung Tischtennis des Berliner Sportvereins SG Bergmann Borsig e.V. aus Pankow</div>
        </div>
        <div class="columns slider-item is-gapless">
          <div class="column is-half slider-image"><img src="<?php echo get_bloginfo('template_url') ?>/images/slider/2.jpg"></div>
          <div class="column is-half slider-text is-size-3-desktop is-size-5-tablet is-size-6-mobile">Durch nachhaltige Jugendförderung gehören wir heute zu den erfolgreichsten Vereinen im Norden Berlins</div>
        </div>
        <div class="columns slider-item is-gapless">
          <div class="column is-half slider-image"><img src="<?php echo get_bloginfo('template_url') ?>/images/slider/3.jpg"></div>
          <div class="column is-half slider-text is-size-3-desktop is-size-5-tablet is-size-6-mobile">Ambitionierte Sportler wie auch Hobbyspieler mit Spaß am Tischtennis sind bei uns herzlich willkommen</div>
        </div>
        <div class="columns slider-item is-gapless">
          <div class="column is-half slider-image"><img src="<?php echo get_bloginfo('template_url') ?>/images/slider/4.jpg"></div>
          <div class="column is-half slider-text is-size-3-desktop is-size-5-tablet is-size-6-mobile">Unsere Herren-, Jugend- und Schülermannschaften spielen in den höchsten Ligen Berlins</div>
        </div>
      </div>
    </div>
  </div>
</div>
