<div id="front">
  <div class="content-left">
    <div id="news">
      <h2 class="page_hdln"><a href="/news">News</a></h2>
      <?php foreach ($posts as $post): ?>
        <article class="pre">
          <header>
            <h3><a href="<?php echo get_permalink($post->ID) ?>"><?php echo $post->post_title ?></a></h3>
            <div class="article-data">
              von <span class="author"><?php echo the_author_meta('nickname', $post->post_author) ?></span>
              <time class="date" pubdate datetime="<?php echo $post->post_date ?>">am <?php echo get_the_date() ?></time>
            </div>
          </header>
          <p class="pre-content">
            <?php echo apply_filters('the_excerpt', wp_trim_words($post->post_content)) ?>
          </p>
        </article>
      <?php endforeach ?>
    </div>
  </div>
  <div class="content-right">
    <img src="<?php echo get_bloginfo('template_url') ?>/images/torte.jpg" class="cake">
    <h2 class="page_hdln">Geburtstagskinder des Monats</h2>
    <table id="bday">
      <?php foreach ($bdays as $bday): ?>
        <tr>
          <td><?php echo date('d.m.Y', strtotime($bday->geburtstag)) ?></td>
          <td><?php echo $bday->vorname ?></td>
          <td><?php echo $bday->name ?></td>
        </tr>
      <?php endforeach ?>
    </table>

    <h2 class="page_hdln">Ergebnisse</h2>
    <table class="team-results zebra">
      <?php foreach ($teams as $team): ?>
        <th class="name" colspan="6"><a href="<?php echo get_permalink($team->ID) ?>"><?php echo $team->post_title ?></a></th>
        <?php foreach ($team->results as $result): $our_team = $team->post_title ?>
          <?php include 'views/result.phtml'; ?>
        <?php endforeach ?>
      <?php endforeach ?>
    </table>
  </div>
  <div class="clearfix"></div>
</div>
