<div id="frontpage-slider">
  <ul id="slider">
    <li>
      <div class="slide-image"><img src="<?php echo get_bloginfo('template_url') ?>/images/slider/1.jpg"></div>
      <div class="slide-text">Wir sind die Abteilung Tischtennis des Berliner Sportvereins SG Bergmann Borsig e.V.</div>
      <div class="clearfix"></div>
    </li>
    <li>
      <div class="slide-image"><img src="<?php echo get_bloginfo('template_url') ?>/images/slider/2.jpg"></div>
      <div class="slide-text">Vor allem wegen unserer guten Förderung junger Talente, gehören wir heute zu den erfolgreichsten Tischtennisvereinen im Norden Berlins</div>
      <div class="clearfix"></div>
    </li>
    <li>
      <div class="slide-image"><img src="<?php echo get_bloginfo('template_url') ?>/images/slider/3.jpg"></div>
      <div class="slide-text">Ambitionierte Sportler wie auch Hobbyspieler mit Spaß am Tischtennis sind bei uns herzlich willkommen</div>
      <div class="clearfix"></div>
    </li>
    <li>
      <div class="slide-image"><img src="<?php echo get_bloginfo('template_url') ?>/images/slider/4.jpg"></div>
      <div class="slide-text">Unsere Herren-, Jugend- und Schülermannschaften spielen in den höchsten Ligen Berlins</div>
      <div class="clearfix"></div>
    </li>
  </ul>
</div>
