<!DOCTYPE html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title><?php bloginfo('name'); if (is_front_page()) echo " &raquo; Tischtennis in Berlin Pankow"; else wp_title() ?></title>
    <meta name="description" content="<?php echo get_post_meta($post->ID, 'meta_description', true) ?: '' ?>" />
    <meta name="robots" content="index,follow">
    <meta name="viewport" content="width=device-width">

    <link rel="stylesheet" href="<?php echo get_bloginfo('template_url') ?>/css/styles.css">

    <?php if (strpos($post->post_content,'[gallery') !== false): ?>
      <script src="<?php echo get_bloginfo('template_url') ?>/js/jquery-1.8.2.min.js"></script>
      <link rel="stylesheet" type="text/css" href="<?php echo content_url() ?>/plugins/lightbox-gallery/lightbox-gallery.css">
      <script src="<?php echo content_url() ?>/plugins/lightbox-gallery/lightbox-gallery.js"></script>
      <script src="<?php echo content_url() ?>/plugins/lightbox-gallery/js/jquery.lightbox.js"></script>
      <script src="<?php echo content_url() ?>/plugins/lightbox-gallery/js/jquery.tooltip.js"></script>
    <?php endif ?>
  </head>
  <body>
    <?php include 'views/google_analytics.phtml' ?>

    <nav class="navbar has-shadow" role="navigation" aria-label="main navigation">
      <div class="container">
        <div class="navbar-brand">
          <a class="navbar-item" href="<?php echo get_bloginfo('siteurl') ?>">
            <img src="<?php echo get_template_directory_uri() . '/images/racket.png' ?>">
            SG Bergmann Borsig e.V.
          </a>

          <a class="navbar-burger" id="toggle-nav">
            <span></span>
            <span></span>
            <span></span>
          </a>
        </div>

        <div class="navbar-menu" id="main-nav">
          <div class="navbar-end">
            <?php foreach (wp_get_nav_menu_items('main-menu') as $item): ?>
              <a href="<?php echo $item->url ?>" class="navbar-item <?php echo $post->ID == $item->object_id ? 'is-active' : '' ?>">
                <?php echo $item->title ?>
              </a>
            <?php endforeach ?>
          </div>
        </div>
      </div>
    </nav>

    <?php if (is_front_page()): ?>
      <?php include 'front_slider.phtml' ?>
    <?php endif ?>

    <div class="main-content container">
