<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">

    <script src="http://use.edgefonts.net/pt-sans.js"></script>
    <link rel="stylesheet" href="<?php echo get_bloginfo('template_url') ?>/css/normalize.min.css">
    <link rel="stylesheet" href="<?php echo get_bloginfo('template_url') ?>/css/main.css">

    <script src="<?php echo get_bloginfo('template_url') ?>/js/modernizr-2.6.1-respond-1.1.0.min.js"></script>
    <script src="<?php echo get_bloginfo('template_url') ?>/js/jquery-1.8.2.min.js"></script>
  </head>
  <body>
    <!--[if lt IE 7]>
        <p class="chromeframe">You are using an outdated browser. <a href="http://browsehappy.com/">Upgrade your browser today</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to better experience this site.</p>
    <![endif]-->
    <header id="header">
      <div id="header_center">
        <figure id="logo"></figure>
        <div id="site"><a href="<?php echo get_bloginfo('siteurl') ?>">SG Bergmann Borsig e.V.</a></div>
        <nav id="nav">
          <?php foreach (wp_get_nav_menu_items('main-menu') as $item): ?>
            <a href="<?php echo $item->url ?>" class="<?php echo $post->ID == $item->object_id ? 'active' : '' ?>">
              <?php echo $item->title ?>
            </a>
          <?php endforeach ?>
        </nav>
      </div>
    </header>
    <div id="main">
