<h1><?php echo $post->post_title ?></h1>
<div id="news">
  <?php foreach ($posts as $post): ?>
    <article class="pre">
      <header><h2><a href="<?php echo get_permalink($post->ID) ?>"><?php echo $post->post_title ?></a></h2></header>
      <p>
        <?php if (strlen($post->post_content) > 200): ?>
          <?php echo substr(strip_tags($post->post_content), 0, 180) ?> <a href="<?php echo get_permalink($post->ID) ?>" class="more">...</a>
        <?php else: ?>
          <?php echo strip_tags($post->post_content) ?>
        <?php endif ?>
      </p>
    </article>
  <?php endforeach ?>
</div>
