<h1><?php echo $post->post_title ?></h1>
<div id="news">
  <?php foreach ($posts as $post): ?>
    <article class="pre">
      <header>
        <h2><a href="<?php echo get_permalink($post->ID) ?>"><?php echo $post->post_title ?></a></h2>
        <div class="article-data">
          von <span class="author"><?php echo the_author_meta('user_nicename', $post->post_author) ?></span>
          <time class="date" pubdate datetime="<?php echo $post->post_date ?>">am <?php echo get_the_date() ?></time>
        </div>
      </header>
      <p class="pre-content">
        <?php echo wp_trim_words($post->post_content) ?>
      </p>
    </article>
  <?php endforeach ?>
</div>
