all:
  hosts:
    borsig-tt.de:
    borsig.local:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    PROJECT_NAME: borsig-tt
    PROJECT_DIR: /srv/borsig
    REPO_DIR_NAME: borsig-theme
    REPO_DIR: "{{ PROJECT_DIR }}/{{ REPO_DIR_NAME }}"

    MYSQL_HOST: db # as defined in docker-compose.yml
    MYSQL_DB_NAME: wordpress
    MYSQL_USER: wordpress

    CONTAINER_THEME_DIR: /var/www/html/wp-content/themes/borsig
