- hosts: all
  name: Set up borsig-tt.de including wordpress, plugins, and the custom theme
  become: yes
  tasks:
    - name: Install required packages
      package:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip
        - docker.io
        - composer
        - git

    - name: Install python docker-compose
      pip:
        name: docker-compose

    - name: Create project dir
      file:
        path: "{{ PROJECT_DIR }}"
        state: directory

    - name: Clone repo
      git:
        repo: https://github.com/jakobw/borsig-tt.git
        dest: "{{ REPO_DIR }}"
        version: master

    - name: Create WordPress uploads dir
      file:
        path: "{{ PROJECT_DIR }}/uploads"
        state: directory

    - name: Create WordPress plugins dir
      file:
        path: "{{ PROJECT_DIR }}/plugins"
        state: directory

    - name: Install WordPress plugins
      unarchive:
        remote_src: true
        src: "{{ item }}"
        dest: "{{ PROJECT_DIR}}/plugins/"
      loop:
        - https://downloads.wordpress.org/plugin/custom-post-type-ui.1.7.4.zip
        - https://downloads.wordpress.org/plugin/lightbox-gallery.0.9.2.zip
        - https://downloads.wordpress.org/plugin/advanced-custom-fields.5.8.12.zip

    - name: Set up docker-compose.yml
      template:
        src: templates/docker-compose.yml.j2
        dest: "{{ PROJECT_DIR }}/docker-compose.yml"

    - name: Copy WordPress Dockerfile
      copy:
        src: files/Dockerfile
        dest: "{{ PROJECT_DIR }}"

    # should be run inside a container so that ideally the host doesn't even need php
    - name: Composer install
      composer:
        command: install
        working_dir: "{{ REPO_DIR }}"

    - name: Set up phinx.yml
      template:
        src: templates/phinx.yml.j2
        dest: "{{ REPO_DIR }}/phinx.yml"

    - name: Run phinx db migrations
      shell: "docker-compose run --rm -w {{ CONTAINER_THEME_DIR }} wordpress vendor/bin/phinx migrate -e production"
      args:
        chdir: "{{ PROJECT_DIR }}"

    - name: docker-compose up
      docker_compose:
        project_src: "{{ PROJECT_DIR }}"
# TODO
# Later:
# - set up match results cron job
# - set up update process (repo, wp, plugins)
# - set up backup process
