- hosts: all
  name: Set up borsig-tt.de including wordpress, plugins, and the custom theme
  become: yes
  tasks:
    - name: Install required packages
      package:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip
        - docker.io
        - composer
        - git

    - name: Install python docker-compose
      pip:
        name: docker-compose

    - name: Create project dir
      file:
        path: "{{ PROJECT_DIR }}"
        state: directory

    - name: Clone repo
      git:
          repo: https://github.com/jakobw/borsig-tt.git
          dest: "{{ REPO_DIR }}"
          version: master

    - name: Set up docker-compose.yml
      template:
        src: templates/docker-compose.yml.j2
        dest: "{{ PROJECT_DIR }}/docker-compose.yml"

    # should be run inside a container so that ideally the host doesn't even need php
    - name: Composer install
      composer:
        command: install
        working_dir: "{{ REPO_DIR }}"

    - name: docker-compose up
      docker_compose:
          project_src: "{{ PROJECT_DIR }}"

# TODO
# Important:
# - install required plugins
# - composer install & phinx

# Later:
# - set up match cron job
# - set up update process (repo, wp, plugins)
# - set up backup process
